# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX = "bento/ubuntu-22.04"

Vagrant.configure("2") do |config|
  config.vm.box = BOX

  config.vm.define :puppet do |puppet|
    puppet.vm.network "public_network", ip: "192.168.3.70", bridge: "eno1"
    puppet.vm.network "forwarded_port", guest: 80, host: 8080
    puppet.vm.hostname = "puppet.local"    

    puppet.vm.synced_folder ".", "/puppet_course"
    puppet.vm.provider :virtualbox do |vb|
      vb.memory = "4096"
    end
 end

  config.vm.define :web do |web|
    web.vm.network "public_network", ip: "192.168.3.62", bridge: "eno1"
    web.vm.hostname = "web.local"
  end

  config.vm.define :db do |db|
    db.vm.network "public_network", ip: "192.168.3.62", bridge: "eno1"
    db.vm.hostname = "db.local"
  end

end

